<?php

return [
    'field_labels' => [
        'employee_number' => 'Employee No.',
        'first_name' => 'First Name',
        'middle_name' => 'Middle Name',
        'last_name' => 'Last Name',
        'suffix' => 'Suffix',
        'is_hybrid' => 'Hybrid Employee',
        'email' => 'Email',
        'phone' => 'Mobile Phone',
        'home_phone' => 'Home Phone',
        'work_phone' => 'Work Phone',
        'fax_number' => 'Fax Number',
        'program' => 'Program',
        'department' => 'Department',
        'college' => 'College',
        'campus' => 'Campus Code',
        'campus_id' => 'Campus',
        'employment_status' => 'Account Status',
        'compliance_status' => 'Compliance Status',
        'is_active' => 'Active Flag',
        'birth_date' => 'Birth Date',
        'place_of_birth' => 'Place of Birth',
        'gender' => 'Gender',
        'civil_status' => 'Civil Status',
        'nationality' => 'Nationality',
        'religion' => 'Religion',
        'language_dialect' => 'Language / Dialect',
        'height_cm' => 'Height (cm)',
        'weight_kg' => 'Weight (kg)',
        'tin_number' => 'TIN',
        'sss_number' => 'SSS No.',
        'philhealth_number' => 'PhilHealth No.',
        'pagibig_number' => 'Pag-IBIG No.',
        'gsis_number' => 'GSIS No.',
        'tax_status' => 'Tax Status',
        'emergency_contact_name' => 'Emergency Contact Name',
        'emergency_contact_relationship' => 'Emergency Contact Relationship',
        'emergency_contact_phone' => 'Emergency Contact Phone',
        'emergency_contact_email' => 'Emergency Contact Email',
        'emergency_contact_address' => 'Emergency Contact Address',
        'address_line' => 'Address Line',
        'country' => 'Country',
        'region' => 'Region',
        'province' => 'Province',
        'city_municipality' => 'City / Municipality',
        'barangay' => 'Barangay',
        'postal_code' => 'Postal Code',
        'extended_profile' => 'Extended Profile',
        'is_confidential' => 'Confidential Record',
        'employment_informations' => 'Employment Information',
        'campus_assignments' => 'Campus Assignments',
        'employee_salaries' => 'Employee Salary',
        'role_id' => 'Access Role',
    ],
];
